spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin123
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        client-id: v-dashboard
        client-secret: v-dashboard-secret

security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
server:
  port: 9090

